SPHINXBUILD   = sphinx-build
SPHINXPROJ    = pytorch_geometric_temporal
SOURCEDIR     = source
BUILDDIR      = build

.PHONY: help Makefile

%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)"
